#!/bin/sh

# Clean up the results directory
rm -rf results
mkdir results

#Synthesize the Wrapper Files
echo 'Synthesizing XST wrapper file (core_top.vhd) with XST';
echo 'Synthesizing example design with XST';
xst -ifn xst.scr
cp ROM_SIN_0_90_top.ngc ./results/


# Copy the netlist generated by Coregen
echo 'Copying files from the netlist directory to the results directory'
cp ../../ROM_SIN_0_90.ngc results/

#  Copy the constraints files generated by Coregen
echo 'Copying files from constraints directory to results directory'
cp ../example_design/ROM_SIN_0_90_top.ucf results/

cd results

echo 'Running ngdbuild'
ngdbuild -p xc6slx100-fgg484-3 ROM_SIN_0_90_top

echo 'Running map'
map ROM_SIN_0_90_top -o mapped.ncd -pr i

echo 'Running par'
par mapped.ncd routed.ncd

echo 'Running trce'
trce -e 10 routed.ncd mapped.pcf -o routed

echo 'Running design through bitgen'
bitgen -w routed

echo 'Running netgen to create gate level Verilog model'
netgen -ofmt verilog -sim -tm ROM_SIN_0_90_top -pcf mapped.pcf -w routed.ncd routed.v
cp routed.sdf ../../production/timing/
